export const products = [
  {
    id: 1,
    name: "Cà phê Robusta Buôn Ma Thuột 500g",
    price: 145000,
    oldPrice: 165000,
    image: "./images/robusta-buon-ma-thuot.jpg",
    shortDescription:
      "Robusta rang mộc đậm vị, hậu chocolate và hương hạt rang.",
    longDescription:
      "Cà phê Robusta Buôn Ma Thuột được rang mộc để giữ lại hương vị tự nhiên của hạt cà phê. Sản phẩm có body dày, vị đắng rõ và hậu vị chocolate đặc trưng, phù hợp với người yêu thích phong cách cà phê Việt Nam đậm đà.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Robusta",
      "Xuất xứ: Buôn Ma Thuột, Việt Nam",
      "Mức rang: Vừa đến đậm",
      "Hương vị: Chocolate, hạt rang, vị đắng đậm",
      "Phù hợp: Pha phin, Moka Pot, Espresso",
    ],
    category: "Cà phê hạt",
    stock: 35,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 2,
    name: "Cà phê Arabica Cầu Đất 500g",
    price: 195000,
    oldPrice: 220000,
    image: "./images/arabica-cau-dat.jpg",
    shortDescription:
      "Arabica thơm nhẹ, chua thanh với hậu vị ngọt và hương trái cây.",
    longDescription:
      "Arabica Cầu Đất nổi bật với hương thơm thanh, độ chua nhẹ và hậu vị ngọt tự nhiên. Hạt được rang ở mức vừa để giữ được những nốt hương trái cây đặc trưng và mang lại trải nghiệm nhẹ nhàng, dễ thưởng thức.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Arabica",
      "Xuất xứ: Cầu Đất, Đà Lạt",
      "Mức rang: Rang vừa",
      "Hương vị: Trái cây, caramel, chua thanh",
      "Phù hợp: V60, Pour Over, French Press",
    ],
    category: "Cà phê hạt",
    stock: 28,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 3,
    name: "Cà phê Blend House 500g",
    price: 175000,
    oldPrice: 190000,
    image: "./images/blend-house.jpg",
    shortDescription:
      "Blend Arabica và Robusta cân bằng giữa hương thơm và vị đậm.",
    longDescription:
      "Blend House là sự kết hợp giữa Arabica thơm nhẹ và Robusta đậm vị. Tỷ lệ phối trộn cân bằng giúp tạo ra tách cà phê có body vừa, hương thơm rõ và hậu vị dễ chịu, phù hợp sử dụng mỗi ngày.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Arabica và Robusta",
      "Mức rang: Rang vừa",
      "Hương vị: Chocolate, caramel, hạt rang",
      "Độ đậm: Trung bình",
      "Phù hợp: Phin, Espresso, Moka Pot",
    ],
    category: "Cà phê hạt",
    stock: 42,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 4,
    name: "Cà phê Robusta Honey 500g",
    price: 185000,
    oldPrice: 0,
    image: "./images/robusta-honey.jpg",
    shortDescription:
      "Robusta chế biến honey với vị đậm và hậu ngọt caramel tự nhiên.",
    longDescription:
      "Robusta Honey được chế biến theo phương pháp honey giúp hạt giữ được vị ngọt tự nhiên rõ hơn. Sản phẩm vẫn mang đặc trưng đậm mạnh của Robusta nhưng có hậu caramel mềm mại và dễ uống hơn.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Robusta",
      "Phương pháp sơ chế: Honey",
      "Mức rang: Rang vừa",
      "Hương vị: Caramel, chocolate, ngọt nhẹ",
      "Phù hợp: Phin, Espresso",
    ],
    category: "Cà phê hạt",
    stock: 20,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 5,
    name: "Cà phê Arabica Typica 250g",
    price: 155000,
    oldPrice: 0,
    image: "./images/arabica-typica.jpg",
    shortDescription:
      "Arabica Typica thơm thanh, chua nhẹ và có hậu vị kéo dài.",
    longDescription:
      "Arabica Typica nổi bật với hương thơm tinh tế, độ chua thanh nhẹ và vị ngọt tự nhiên. Đây là dòng cà phê phù hợp với người muốn khám phá những tầng hương nhẹ nhàng của Arabica.",
    details: [
      "Khối lượng: 250g",
      "Loại hạt: Arabica Typica",
      "Mức rang: Sáng đến vừa",
      "Hương vị: Hoa, trái cây, ngọt nhẹ",
      "Độ chua: Thanh nhẹ",
      "Phù hợp: V60, Pour Over",
    ],
    category: "Cà phê hạt",
    stock: 18,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 6,
    name: "Cà phê Arabica Bourbon 250g",
    price: 165000,
    oldPrice: 180000,
    image: "./images/arabica-bourbon.jpg",
    shortDescription:
      "Arabica Bourbon có hương hoa, trái cây chín và vị ngọt nhẹ.",
    longDescription:
      "Arabica Bourbon mang hương hoa nhẹ kết hợp với những nốt hương trái cây chín. Vị cà phê mềm, độ chua cân bằng và hậu vị ngọt tự nhiên tạo nên trải nghiệm tinh tế.",
    details: [
      "Khối lượng: 250g",
      "Loại hạt: Arabica Bourbon",
      "Mức rang: Rang vừa",
      "Hương vị: Hoa, trái cây chín, caramel",
      "Độ chua: Trung bình",
      "Phù hợp: Pour Over, V60, French Press",
    ],
    category: "Cà phê hạt",
    stock: 15,
    hot: false,
    newProduct: true,
    sale: true,
  },

  {
    id: 7,
    name: "Cà phê Espresso Blend 500g",
    price: 185000,
    oldPrice: 210000,
    image: "./images/espresso-blend.jpg",
    shortDescription:
      "Blend dành cho Espresso với body dày, crema tốt và vị chocolate.",
    longDescription:
      "Espresso Blend được phối trộn để tạo ra tách Espresso có body dày, crema ổn định và hương vị cân bằng. Những nốt chocolate và hạt rang giúp cà phê giữ được vị rõ ngay cả khi kết hợp cùng sữa.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Blend Arabica và Robusta",
      "Mức rang: Vừa đến đậm",
      "Hương vị: Chocolate, caramel, hạt rang",
      "Body: Dày",
      "Phù hợp: Espresso, Latte, Cappuccino",
    ],
    category: "Cà phê hạt",
    stock: 36,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 8,
    name: "Cà phê Ethiopia Sidamo 250g",
    price: 245000,
    oldPrice: 0,
    image: "./images/ethiopia-sidamo.jpg",
    shortDescription:
      "Cà phê Ethiopia với hương hoa, cam chanh và vị chua thanh.",
    longDescription:
      "Ethiopia Sidamo nổi bật với hương hoa nhẹ và các nốt hương cam chanh đặc trưng. Độ chua tươi sáng kết hợp cùng hậu vị sạch tạo nên trải nghiệm cà phê khác biệt và tinh tế.",
    details: [
      "Khối lượng: 250g",
      "Xuất xứ: Ethiopia",
      "Vùng trồng: Sidamo",
      "Mức rang: Rang sáng",
      "Hương vị: Hoa, cam chanh, trái cây",
      "Phù hợp: V60, Pour Over",
    ],
    category: "Cà phê hạt",
    stock: 12,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 9,
    name: "Cà phê Colombia Supremo 250g",
    price: 225000,
    oldPrice: 245000,
    image: "./images/colombia-supremo.jpg",
    shortDescription:
      "Cà phê Colombia cân bằng với hương caramel, hạt dẻ và chocolate.",
    longDescription:
      "Colombia Supremo có hương vị cân bằng giữa độ chua nhẹ, vị ngọt và body vừa. Những nốt caramel, chocolate và hạt dẻ giúp sản phẩm dễ tiếp cận với nhiều người uống cà phê.",
    details: [
      "Khối lượng: 250g",
      "Xuất xứ: Colombia",
      "Loại hạt: Arabica",
      "Mức rang: Rang vừa",
      "Hương vị: Caramel, hạt dẻ, chocolate",
      "Phù hợp: Pour Over, French Press, Espresso",
    ],
    category: "Cà phê hạt",
    stock: 17,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 10,
    name: "Cà phê Brazil Santos 500g",
    price: 210000,
    oldPrice: 230000,
    image: "./images/brazil-santos.jpg",
    shortDescription:
      "Hương chocolate và caramel, độ chua thấp, dễ uống mỗi ngày.",
    longDescription:
      "Brazil Santos là dòng cà phê có độ chua thấp và hương vị êm dịu. Chocolate, caramel và hạt rang là những nốt hương nổi bật, phù hợp với người thích cà phê dễ uống và cân bằng.",
    details: [
      "Khối lượng: 500g",
      "Xuất xứ: Brazil",
      "Loại hạt: Arabica",
      "Mức rang: Rang vừa",
      "Hương vị: Chocolate, caramel, hạt rang",
      "Phù hợp: Espresso, French Press, Moka Pot",
    ],
    category: "Cà phê hạt",
    stock: 24,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 11,
    name: "Cà phê Robusta xay phin 500g",
    price: 135000,
    oldPrice: 150000,
    image: "./images/robusta-xay-phin.jpg",
    shortDescription:
      "Robusta rang xay sẵn, đậm vị và phù hợp pha phin truyền thống.",
    longDescription:
      "Robusta được rang và xay sẵn với kích thước phù hợp cho phin cà phê Việt Nam. Sản phẩm có vị đắng mạnh, body dày và hương cà phê rang rõ nét, tiện lợi để sử dụng hằng ngày.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Robusta",
      "Dạng sản phẩm: Cà phê xay",
      "Độ xay: Pha phin",
      "Mức rang: Rang đậm",
      "Phù hợp: Phin truyền thống",
    ],
    category: "Cà phê xay",
    stock: 45,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 12,
    name: "Cà phê Arabica xay phin 500g",
    price: 185000,
    oldPrice: 0,
    image: "./images/arabica-xay-phin.jpg",
    shortDescription:
      "Arabica rang vừa, xay sẵn với hương thơm nhẹ và vị dễ uống.",
    longDescription:
      "Arabica được rang ở mức vừa và xay sẵn để sử dụng với phin cà phê. Hương thơm thanh, độ chua nhẹ và hậu vị ngọt giúp tách cà phê mềm hơn so với Robusta truyền thống.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Arabica",
      "Dạng sản phẩm: Cà phê xay",
      "Độ xay: Pha phin",
      "Mức rang: Rang vừa",
      "Hương vị: Thơm nhẹ, chua thanh",
    ],
    category: "Cà phê xay",
    stock: 30,
    hot: false,
    newProduct: false,
    sale: false,
  },

  {
    id: 13,
    name: "Cà phê Blend truyền thống 500g",
    price: 155000,
    oldPrice: 175000,
    image: "./images/blend-truyen-thong.jpg",
    shortDescription:
      "Blend rang đậm mang phong cách cà phê Việt Nam truyền thống.",
    longDescription:
      "Blend truyền thống được phối trộn để tạo ra vị cà phê đậm, thơm và có body rõ. Mức rang đậm phù hợp với cách pha phin quen thuộc và có thể uống đen hoặc kết hợp cùng sữa đặc.",
    details: [
      "Khối lượng: 500g",
      "Loại hạt: Blend",
      "Dạng sản phẩm: Cà phê xay",
      "Mức rang: Rang đậm",
      "Hương vị: Đậm, chocolate, hạt rang",
      "Phù hợp: Pha phin",
    ],
    category: "Cà phê xay",
    stock: 50,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 14,
    name: "Cà phê Espresso xay máy 500g",
    price: 175000,
    oldPrice: 195000,
    image: "./images/espresso-xay.jpg",
    shortDescription: "Cà phê xay mịn dành cho máy Espresso gia đình.",
    longDescription:
      "Cà phê được xay ở độ mịn phù hợp với các dòng máy Espresso gia đình. Hương vị đậm, body tốt và hậu chocolate giúp tạo ra Espresso cân bằng mà không cần sử dụng máy xay riêng.",
    details: [
      "Khối lượng: 500g",
      "Dạng sản phẩm: Cà phê xay",
      "Độ xay: Espresso",
      "Mức rang: Vừa đến đậm",
      "Hương vị: Chocolate, caramel",
      "Phù hợp: Máy Espresso",
    ],
    category: "Cà phê xay",
    stock: 27,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 15,
    name: "Cà phê Moka Cầu Đất xay 250g",
    price: 185000,
    oldPrice: 0,
    image: "./images/moka-cau-dat.jpg",
    shortDescription: "Moka Cầu Đất thơm dịu với vị thanh và hậu ngọt nhẹ.",
    longDescription:
      "Moka Cầu Đất có hương thơm đặc trưng, vị thanh và hậu ngọt nhẹ nhàng. Sản phẩm đã được rang và xay sẵn, phù hợp với người yêu thích cà phê thơm nhưng không quá đắng.",
    details: [
      "Khối lượng: 250g",
      "Loại hạt: Moka",
      "Xuất xứ: Cầu Đất, Đà Lạt",
      "Dạng sản phẩm: Cà phê xay",
      "Mức rang: Rang vừa",
      "Hương vị: Thơm nhẹ, ngọt thanh",
    ],
    category: "Cà phê xay",
    stock: 14,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 16,
    name: "Cà phê Decaf 250g",
    price: 210000,
    oldPrice: 230000,
    image: "./images/decaf.jpg",
    shortDescription:
      "Cà phê giảm caffeine nhưng vẫn giữ được hương vị đặc trưng.",
    longDescription:
      "Cà phê Decaf đã được xử lý để loại bỏ phần lớn caffeine nhưng vẫn giữ lại hương thơm và vị cà phê tự nhiên. Sản phẩm phù hợp với người muốn hạn chế lượng caffeine nhưng vẫn muốn thưởng thức cà phê.",
    details: [
      "Khối lượng: 250g",
      "Dạng sản phẩm: Cà phê xay",
      "Caffeine: Đã giảm phần lớn",
      "Mức rang: Rang vừa",
      "Hương vị: Dịu, cân bằng",
      "Phù hợp: Sử dụng nhiều thời điểm trong ngày",
    ],
    category: "Cà phê xay",
    stock: 16,
    hot: false,
    newProduct: true,
    sale: true,
  },

  {
    id: 17,
    name: "Cà phê Drip Bag Arabica 10 gói",
    price: 125000,
    oldPrice: 140000,
    image: "./images/drip-bag-arabica.jpg",
    shortDescription:
      "Arabica túi lọc tiện lợi, chỉ cần nước nóng để thưởng thức.",
    longDescription:
      "Drip Bag Arabica được đóng thành từng túi lọc riêng giúp việc pha cà phê trở nên nhanh và đơn giản. Chỉ cần đặt túi lên cốc và rót nước nóng từ từ là có thể thưởng thức.",
    details: [
      "Quy cách: 10 gói",
      "Loại cà phê: Arabica",
      "Dạng sản phẩm: Túi lọc",
      "Cách pha: Rót nước nóng trực tiếp",
      "Hương vị: Thơm nhẹ, chua thanh",
      "Phù hợp: Nhà, văn phòng, du lịch",
    ],
    category: "Drip Bag",
    stock: 60,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 18,
    name: "Cà phê Drip Bag Robusta 10 gói",
    price: 105000,
    oldPrice: 120000,
    image: "./images/drip-bag-robusta.jpg",
    shortDescription:
      "Robusta túi lọc rang đậm dành cho người thích cà phê mạnh.",
    longDescription:
      "Drip Bag Robusta mang đến cách pha tiện lợi nhưng vẫn giữ được phong cách cà phê đậm vị. Robusta rang đậm tạo body rõ, vị đắng mạnh và hậu hương hạt rang.",
    details: [
      "Quy cách: 10 gói",
      "Loại cà phê: Robusta",
      "Dạng sản phẩm: Túi lọc",
      "Mức rang: Rang đậm",
      "Hương vị: Đậm, đắng, hạt rang",
      "Cách pha: Rót nước nóng",
    ],
    category: "Drip Bag",
    stock: 55,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 19,
    name: "Cà phê Drip Bag Ethiopia 5 gói",
    price: 95000,
    oldPrice: 0,
    image: "./images/drip-bag-ethiopia.jpg",
    shortDescription:
      "Drip Bag Ethiopia thơm hương hoa và trái cây, tiện lợi mang theo.",
    longDescription:
      "Drip Bag Ethiopia mang đến hương hoa và trái cây đặc trưng trong hình thức túi lọc tiện lợi. Mỗi gói được định lượng sẵn để người dùng dễ dàng pha một cốc cà phê ở bất kỳ đâu.",
    details: [
      "Quy cách: 5 gói",
      "Xuất xứ cà phê: Ethiopia",
      "Dạng sản phẩm: Túi lọc",
      "Hương vị: Hoa, trái cây, cam chanh",
      "Cách pha: Rót nước nóng",
      "Phù hợp: Văn phòng, du lịch",
    ],
    category: "Drip Bag",
    stock: 25,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 20,
    name: "Combo Drip Bag 5 vị",
    price: 145000,
    oldPrice: 165000,
    image: "./images/combo-drip-bag.jpg",
    shortDescription:
      "Combo nhiều hương vị Drip Bag dành cho người thích trải nghiệm.",
    longDescription:
      "Combo Drip Bag gồm nhiều loại cà phê với đặc điểm hương vị khác nhau. Mỗi túi được đóng riêng và có thể pha trực tiếp trên cốc, giúp người dùng dễ dàng khám phá nhiều phong cách cà phê.",
    details: [
      "Số loại: 5 hương vị",
      "Dạng sản phẩm: Drip Bag",
      "Cách pha: Rót nước nóng",
      "Dụng cụ cần thiết: Cốc",
      "Phù hợp: Trải nghiệm nhiều loại cà phê",
      "Gợi ý: Có thể dùng làm quà tặng",
    ],
    category: "Drip Bag",
    stock: 32,
    hot: true,
    newProduct: true,
    sale: true,
  },

  {
    id: 21,
    name: "Cold Brew Arabica 5 túi lọc",
    price: 135000,
    oldPrice: 150000,
    image: "./images/cold-brew-arabica.jpg",
    shortDescription: "Arabica túi lọc chuyên dùng để pha cold brew tại nhà.",
    longDescription:
      "Cold Brew Arabica được đóng thành túi lọc định lượng sẵn để pha cà phê lạnh đơn giản tại nhà. Chỉ cần ngâm trong nước lạnh từ 8 đến 12 giờ rồi lấy túi ra và thưởng thức.",
    details: [
      "Quy cách: 5 túi lọc",
      "Loại cà phê: Arabica",
      "Phương pháp pha: Cold Brew",
      "Thời gian ngâm: 8 - 12 giờ",
      "Hương vị: Thanh, thơm nhẹ",
      "Bảo quản sau pha: Trong tủ lạnh",
    ],
    category: "Cold Brew",
    stock: 33,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 22,
    name: "Cold Brew Blend 10 túi lọc",
    price: 195000,
    oldPrice: 220000,
    image: "./images/cold-brew-blend.jpg",
    shortDescription:
      "Blend rang vừa đóng túi tiện lợi để pha cold brew tại nhà.",
    longDescription:
      "Cold Brew Blend kết hợp nhiều loại cà phê nhằm tạo sự cân bằng giữa hương thơm, vị đậm và hậu ngọt. Túi lọc được định lượng sẵn giúp việc pha cold brew trở nên đơn giản và ổn định.",
    details: [
      "Quy cách: 10 túi lọc",
      "Loại cà phê: Blend",
      "Phương pháp pha: Cold Brew",
      "Thời gian ngâm: 8 - 12 giờ",
      "Hương vị: Cân bằng, hậu ngọt",
      "Phù hợp: Pha lạnh tại nhà",
    ],
    category: "Cold Brew",
    stock: 29,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 23,
    name: "Cold Brew Ethiopia 5 túi lọc",
    price: 165000,
    oldPrice: 0,
    image: "./images/cold-brew-ethiopia.jpg",
    shortDescription:
      "Cold Brew Ethiopia có hương trái cây rõ và vị chua thanh.",
    longDescription:
      "Cold Brew Ethiopia nổi bật với hương trái cây và độ chua tươi sáng khi được chiết xuất lạnh. Phương pháp ngâm lạnh giúp vị cà phê trở nên êm và nhẹ hơn so với pha nóng.",
    details: [
      "Quy cách: 5 túi lọc",
      "Xuất xứ cà phê: Ethiopia",
      "Phương pháp pha: Cold Brew",
      "Thời gian ngâm: 8 - 12 giờ",
      "Hương vị: Trái cây, cam chanh",
      "Độ chua: Thanh",
    ],
    category: "Cold Brew",
    stock: 19,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 24,
    name: "Cà phê hòa tan đen 20 gói",
    price: 89000,
    oldPrice: 99000,
    image: "./images/hoa-tan-den.jpg",
    shortDescription:
      "Cà phê hòa tan nguyên chất không đường, tiện lợi cho văn phòng.",
    longDescription:
      "Cà phê hòa tan đen được đóng thành từng gói riêng, phù hợp cho nhu cầu sử dụng nhanh và tiện lợi. Sản phẩm không bổ sung đường, giúp giữ được vị cà phê đậm rõ.",
    details: [
      "Quy cách: 20 gói",
      "Dạng sản phẩm: Hòa tan",
      "Đường: Không đường",
      "Cách pha: Pha với nước nóng",
      "Hương vị: Đậm",
      "Phù hợp: Nhà và văn phòng",
    ],
    category: "Cà phê hòa tan",
    stock: 70,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 25,
    name: "Cà phê hòa tan 3in1 20 gói",
    price: 95000,
    oldPrice: 110000,
    image: "./images/hoa-tan-3in1.jpg",
    shortDescription:
      "Cà phê 3in1 kết hợp cà phê, đường và sữa với vị dễ uống.",
    longDescription:
      "Cà phê hòa tan 3in1 kết hợp cà phê, đường và sữa theo tỷ lệ cân bằng. Hương vị ngọt nhẹ, dễ uống và thuận tiện cho người cần một tách cà phê nhanh.",
    details: [
      "Quy cách: 20 gói",
      "Dạng sản phẩm: Hòa tan 3in1",
      "Thành phần chính: Cà phê, đường, sữa",
      "Cách pha: Pha với nước nóng",
      "Hương vị: Ngọt nhẹ",
      "Phù hợp: Sử dụng hằng ngày",
    ],
    category: "Cà phê hòa tan",
    stock: 80,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 26,
    name: "Cà phê hòa tan Cappuccino 12 gói",
    price: 115000,
    oldPrice: 0,
    image: "./images/cappuccino-hoa-tan.jpg",
    shortDescription: "Cappuccino hòa tan với vị sữa nhẹ và lớp bọt mềm.",
    longDescription:
      "Cappuccino hòa tan mang đến hương vị cà phê kết hợp cùng sữa nhẹ nhàng. Khi pha với nước nóng, sản phẩm tạo lớp bọt mềm trên bề mặt và phù hợp với người thích cà phê nhẹ.",
    details: [
      "Quy cách: 12 gói",
      "Dạng sản phẩm: Cappuccino hòa tan",
      "Cách pha: Pha với nước nóng",
      "Hương vị: Cà phê sữa nhẹ",
      "Đặc điểm: Có lớp bọt",
      "Phù hợp: Người thích cà phê nhẹ",
    ],
    category: "Cà phê hòa tan",
    stock: 48,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 27,
    name: "Viên nén Espresso Intenso 10 viên",
    price: 135000,
    oldPrice: 150000,
    image: "./images/capsule-intenso.jpg",
    shortDescription:
      "Viên nén Espresso đậm vị dành cho máy capsule tương thích.",
    longDescription:
      "Espresso Intenso được đóng thành từng viên nén giúp pha cà phê nhanh chóng và ổn định. Hương vị đậm, body rõ và hậu hương hạt rang phù hợp với người thích Espresso mạnh.",
    details: [
      "Quy cách: 10 viên",
      "Dạng sản phẩm: Capsule",
      "Cường độ: Đậm",
      "Hương vị: Chocolate, hạt rang",
      "Cách pha: Máy capsule",
      "Phù hợp: Espresso",
    ],
    category: "Capsule",
    stock: 45,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 28,
    name: "Viên nén Espresso Arabica 10 viên",
    price: 145000,
    oldPrice: 0,
    image: "./images/capsule-arabica.jpg",
    shortDescription: "Capsule Arabica rang vừa với hương thơm và vị cân bằng.",
    longDescription:
      "Viên nén Espresso Arabica sử dụng cà phê rang vừa để giữ hương thơm đặc trưng. Vị cà phê cân bằng và nhẹ hơn dòng Intenso, phù hợp với người thích Espresso dễ uống.",
    details: [
      "Quy cách: 10 viên",
      "Loại cà phê: Arabica",
      "Dạng sản phẩm: Capsule",
      "Mức rang: Rang vừa",
      "Hương vị: Thơm nhẹ, cân bằng",
      "Cách pha: Máy capsule",
    ],
    category: "Capsule",
    stock: 38,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 29,
    name: "Viên nén Lungo 10 viên",
    price: 139000,
    oldPrice: 155000,
    image: "./images/capsule-lungo.jpg",
    shortDescription: "Capsule Lungo với hương caramel và hạt rang nhẹ.",
    longDescription:
      "Viên nén Lungo được thiết kế để pha lượng nước lớn hơn Espresso thông thường. Hương caramel kết hợp cùng hạt rang tạo nên tách cà phê cân bằng và dễ uống.",
    details: [
      "Quy cách: 10 viên",
      "Dạng sản phẩm: Capsule",
      "Kiểu pha: Lungo",
      "Hương vị: Caramel, hạt rang",
      "Cường độ: Trung bình",
      "Cách pha: Máy capsule",
    ],
    category: "Capsule",
    stock: 34,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 30,
    name: "Phin cà phê nhôm truyền thống",
    price: 45000,
    oldPrice: 55000,
    image: "./images/phin-nhom.jpg",
    shortDescription:
      "Phin nhôm nhỏ gọn dành cho cách pha cà phê Việt Nam truyền thống.",
    longDescription:
      "Phin cà phê nhôm có thiết kế đơn giản, nhẹ và dễ sử dụng. Sản phẩm phù hợp với người muốn pha cà phê theo phong cách Việt Nam truyền thống tại nhà hoặc văn phòng.",
    details: [
      "Chất liệu: Nhôm",
      "Loại dụng cụ: Phin cà phê",
      "Màu sắc: Bạc",
      "Cách sử dụng: Pha trực tiếp trên cốc",
      "Phù hợp: Cà phê xay phin",
      "Đặc điểm: Nhẹ, dễ vệ sinh",
    ],
    category: "Dụng cụ pha",
    stock: 65,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 31,
    name: "Phin cà phê inox",
    price: 95000,
    oldPrice: 110000,
    image: "./images/phin-inox.jpg",
    shortDescription: "Phin inox chắc chắn, bền và dễ vệ sinh sau khi sử dụng.",
    longDescription:
      "Phin cà phê inox có độ bền cao và phù hợp với nhu cầu sử dụng lâu dài. Thiết kế lỗ lọc đều giúp quá trình chiết xuất ổn định và bề mặt inox dễ vệ sinh.",
    details: [
      "Chất liệu: Inox",
      "Loại dụng cụ: Phin cà phê",
      "Màu sắc: Bạc",
      "Đặc điểm: Bền, dễ vệ sinh",
      "Cách sử dụng: Pha trực tiếp trên cốc",
      "Phù hợp: Cà phê xay phin",
    ],
    category: "Dụng cụ pha",
    stock: 43,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 32,
    name: "Bình pha cà phê V60",
    price: 165000,
    oldPrice: 185000,
    image: "./images/v60.jpg",
    shortDescription:
      "Dụng cụ V60 dành cho người yêu thích phong cách Pour Over.",
    longDescription:
      "V60 là dụng cụ pha cà phê thủ công dạng hình nón giúp người dùng chủ động kiểm soát dòng nước và quá trình chiết xuất. Phương pháp này giúp làm nổi bật hương thơm và độ trong của cà phê.",
    details: [
      "Loại dụng cụ: Phễu V60",
      "Phương pháp pha: Pour Over",
      "Giấy lọc: Có sử dụng",
      "Độ khó: Cơ bản đến trung bình",
      "Phù hợp: Arabica rang sáng và vừa",
      "Sử dụng: Pha thủ công",
    ],
    category: "Dụng cụ pha",
    stock: 24,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 33,
    name: "Giấy lọc V60 100 tờ",
    price: 85000,
    oldPrice: 0,
    image: "./images/filter-v60.jpg",
    shortDescription: "Giấy lọc chuyên dụng dành cho phễu pha cà phê V60.",
    longDescription:
      "Giấy lọc V60 được thiết kế phù hợp với hình dạng của phễu V60. Giấy giúp giữ lại bột cà phê và một phần dầu trong quá trình pha để tạo tách cà phê sạch và trong hơn.",
    details: [
      "Số lượng: 100 tờ",
      "Loại sản phẩm: Giấy lọc",
      "Dụng cụ tương thích: V60",
      "Màu sắc: Trắng",
      "Cách sử dụng: Dùng một lần",
      "Phù hợp: Pour Over",
    ],
    category: "Dụng cụ pha",
    stock: 55,
    hot: false,
    newProduct: false,
    sale: false,
  },

  {
    id: 34,
    name: "Bình French Press 600ml",
    price: 245000,
    oldPrice: 280000,
    image: "./images/french-press.jpg",
    shortDescription:
      "French Press thủy tinh 600ml dùng để pha cà phê hoặc trà.",
    longDescription:
      "French Press sử dụng phương pháp ngâm cà phê trực tiếp trong nước nóng sau đó ép bã bằng lưới lọc. Phương pháp này giúp giữ được nhiều dầu tự nhiên và tạo body đầy đặn.",
    details: [
      "Dung tích: 600ml",
      "Loại dụng cụ: French Press",
      "Chất liệu bình: Thủy tinh",
      "Phương pháp pha: Ngâm",
      "Số lượng phục vụ: 2 - 3 cốc",
      "Phù hợp: Cà phê và trà",
    ],
    category: "Dụng cụ pha",
    stock: 20,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 35,
    name: "Bình Moka Pot 3 Cup",
    price: 295000,
    oldPrice: 325000,
    image: "./images/moka-pot.jpg",
    shortDescription:
      "Moka Pot 3 Cup pha cà phê đậm phong cách Ý ngay trên bếp.",
    longDescription:
      "Moka Pot sử dụng áp suất hơi nước để chiết xuất cà phê, tạo hương vị đậm và mạnh hơn các phương pháp lọc thông thường. Phiên bản 3 Cup phù hợp với nhu cầu sử dụng cá nhân hoặc gia đình nhỏ.",
    details: [
      "Dung tích: 3 Cup",
      "Loại dụng cụ: Moka Pot",
      "Chất liệu: Hợp kim nhôm",
      "Phương pháp pha: Áp suất hơi nước",
      "Phù hợp: Cà phê rang vừa đến đậm",
      "Sử dụng: Trên bếp",
    ],
    category: "Dụng cụ pha",
    stock: 18,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 36,
    name: "Bình Cold Brew 1L",
    price: 225000,
    oldPrice: 0,
    image: "./images/binh-cold-brew.jpg",
    shortDescription:
      "Bình pha cold brew 1L có lõi lọc, tiện lợi sử dụng tại nhà.",
    longDescription:
      "Bình Cold Brew dung tích 1 lít được trang bị lõi lọc giúp ngâm cà phê trực tiếp trong nước lạnh. Thiết kế đơn giản giúp việc pha và vệ sinh trở nên thuận tiện.",
    details: [
      "Dung tích: 1L",
      "Loại dụng cụ: Bình Cold Brew",
      "Lõi lọc: Có",
      "Phương pháp pha: Ngâm lạnh",
      "Thời gian pha: 8 - 12 giờ",
      "Phù hợp: Sử dụng tại nhà",
    ],
    category: "Dụng cụ pha",
    stock: 22,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 37,
    name: "Cân điện tử pha cà phê",
    price: 185000,
    oldPrice: 210000,
    image: "./images/can-ca-phe.jpg",
    shortDescription:
      "Cân điện tử nhỏ gọn giúp kiểm soát lượng cà phê và nước chính xác.",
    longDescription:
      "Cân điện tử hỗ trợ người dùng đo chính xác lượng cà phê và nước trong quá trình pha. Việc kiểm soát tỷ lệ giúp công thức pha ổn định và dễ lặp lại hơn.",
    details: [
      "Loại sản phẩm: Cân điện tử",
      "Chức năng: Đo khối lượng",
      "Hiển thị: Màn hình điện tử",
      "Ứng dụng: Pha cà phê",
      "Phù hợp: V60, Espresso, French Press",
      "Thiết kế: Nhỏ gọn",
    ],
    category: "Dụng cụ pha",
    stock: 26,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 38,
    name: "Ấm rót cổ ngỗng 600ml",
    price: 275000,
    oldPrice: 310000,
    image: "./images/am-co-ngong.jpg",
    shortDescription: "Ấm cổ ngỗng giúp kiểm soát dòng nước khi pha Pour Over.",
    longDescription:
      "Ấm rót cổ ngỗng có vòi nhỏ và dài giúp người dùng kiểm soát tốc độ cũng như vị trí dòng nước khi pha. Đây là dụng cụ đặc biệt phù hợp với các phương pháp Pour Over.",
    details: [
      "Dung tích: 600ml",
      "Loại sản phẩm: Ấm rót",
      "Thiết kế vòi: Cổ ngỗng",
      "Chức năng: Kiểm soát dòng nước",
      "Phù hợp: V60, Pour Over",
      "Sử dụng: Pha cà phê thủ công",
    ],
    category: "Dụng cụ pha",
    stock: 16,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 39,
    name: "Máy xay cà phê cầm tay",
    price: 395000,
    oldPrice: 450000,
    image: "./images/may-xay-cam-tay.jpg",
    shortDescription:
      "Máy xay thủ công có thể điều chỉnh độ mịn cho nhiều cách pha.",
    longDescription:
      "Máy xay cà phê cầm tay giúp người dùng xay hạt ngay trước khi pha để giữ hương thơm tốt hơn. Độ mịn có thể điều chỉnh để phù hợp với nhiều phương pháp pha khác nhau.",
    details: [
      "Loại máy: Xay thủ công",
      "Nguồn điện: Không sử dụng điện",
      "Điều chỉnh độ mịn: Có",
      "Dạng sử dụng: Cầm tay",
      "Phù hợp: Phin, V60, French Press",
      "Ưu điểm: Nhỏ gọn, dễ mang theo",
    ],
    category: "Máy xay",
    stock: 21,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 40,
    name: "Máy xay cà phê điện mini",
    price: 490000,
    oldPrice: 550000,
    image: "./images/may-xay-dien.jpg",
    shortDescription:
      "Máy xay điện nhỏ gọn phù hợp sử dụng tại nhà và văn phòng.",
    longDescription:
      "Máy xay cà phê điện mini giúp quá trình chuẩn bị cà phê trở nên nhanh chóng hơn. Kích thước nhỏ gọn phù hợp đặt tại nhà hoặc văn phòng và thích hợp với người thường xuyên sử dụng cà phê hạt.",
    details: [
      "Loại máy: Máy xay điện",
      "Nguồn điện: Điện",
      "Thiết kế: Mini",
      "Chức năng: Xay hạt cà phê",
      "Phù hợp: Nhà và văn phòng",
      "Ưu điểm: Nhanh và tiện lợi",
    ],
    category: "Máy xay",
    stock: 14,
    hot: false,
    newProduct: true,
    sale: true,
  },

  {
    id: 41,
    name: "Ly giữ nhiệt Coffee 500ml",
    price: 189000,
    oldPrice: 220000,
    image: "./images/ly-giu-nhiet.jpg",
    shortDescription:
      "Ly giữ nhiệt 500ml thích hợp mang cà phê đi học hoặc đi làm.",
    longDescription:
      "Ly giữ nhiệt Coffee có dung tích 500ml, phù hợp để mang cà phê nóng hoặc lạnh khi di chuyển. Thiết kế nắp kín giúp việc mang theo thuận tiện hơn trong sinh hoạt hằng ngày.",
    details: [
      "Dung tích: 500ml",
      "Chất liệu: Inox",
      "Khả năng giữ nhiệt: Nóng và lạnh",
      "Nắp đậy: Có",
      "Phù hợp: Đi học, đi làm",
      "Loại sản phẩm: Ly giữ nhiệt",
    ],
    category: "Phụ kiện",
    stock: 37,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 42,
    name: "Cốc sứ Coffee Lover",
    price: 99000,
    oldPrice: 0,
    image: "./images/coc-su.jpg",
    shortDescription:
      "Cốc sứ 350ml thiết kế đơn giản dành cho người yêu cà phê.",
    longDescription:
      "Cốc sứ Coffee Lover có dung tích 350ml, phù hợp với cà phê, trà và các loại thức uống nóng. Kiểu dáng đơn giản giúp sản phẩm dễ sử dụng trong nhiều không gian khác nhau.",
    details: [
      "Dung tích: 350ml",
      "Chất liệu: Sứ",
      "Loại sản phẩm: Cốc uống cà phê",
      "Tay cầm: Có",
      "Phù hợp: Đồ uống nóng",
      "Gợi ý: Sử dụng cá nhân hoặc làm quà",
    ],
    category: "Phụ kiện",
    stock: 40,
    hot: false,
    newProduct: true,
    sale: false,
  },

  {
    id: 43,
    name: "Hũ thủy tinh đựng cà phê 500ml",
    price: 85000,
    oldPrice: 99000,
    image: "./images/hu-thuy-tinh.jpg",
    shortDescription:
      "Hũ thủy tinh kín khí giúp bảo quản cà phê sau khi mở túi.",
    longDescription:
      "Hũ thủy tinh dung tích 500ml được thiết kế để bảo quản cà phê và các loại thực phẩm khô. Nắp kín giúp hạn chế không khí và độ ẩm tiếp xúc với sản phẩm.",
    details: [
      "Dung tích: 500ml",
      "Chất liệu: Thủy tinh",
      "Nắp đậy: Kín",
      "Loại sản phẩm: Hũ bảo quản",
      "Phù hợp: Cà phê hạt và cà phê xay",
      "Đặc điểm: Trong suốt, dễ vệ sinh",
    ],
    category: "Phụ kiện",
    stock: 35,
    hot: false,
    newProduct: false,
    sale: true,
  },

  {
    id: 44,
    name: "Muỗng đong cà phê inox",
    price: 39000,
    oldPrice: 0,
    image: "./images/muong-dong.jpg",
    shortDescription: "Muỗng inox tiện lợi để đong lượng cà phê trước khi pha.",
    longDescription:
      "Muỗng đong cà phê inox giúp người dùng định lượng cà phê thuận tiện hơn trong quá trình pha. Chất liệu inox bền, dễ vệ sinh và có thể sử dụng nhiều lần.",
    details: [
      "Chất liệu: Inox",
      "Loại sản phẩm: Muỗng đong",
      "Công dụng: Định lượng cà phê",
      "Tái sử dụng: Có",
      "Đặc điểm: Dễ vệ sinh",
      "Phù hợp: Phin, Pour Over",
    ],
    category: "Phụ kiện",
    stock: 75,
    hot: false,
    newProduct: false,
    sale: false,
  },

  {
    id: 45,
    name: "Combo cà phê Việt",
    price: 269000,
    oldPrice: 310000,
    image: "./images/combo-ca-phe-viet.jpg",
    shortDescription:
      "Combo cà phê rang xay và phin dành cho người thích cà phê Việt.",
    longDescription:
      "Combo cà phê Việt cung cấp những sản phẩm cơ bản để bắt đầu pha cà phê phin tại nhà. Bộ sản phẩm phù hợp cho người yêu thích phong cách cà phê Việt Nam đậm đà và truyền thống.",
    details: [
      "Sản phẩm gồm: Robusta 500g",
      "Sản phẩm gồm: Blend 500g",
      "Dụng cụ kèm theo: Phin nhôm",
      "Số lượng: 3 sản phẩm",
      "Phong cách: Cà phê Việt Nam",
      "Phù hợp: Sử dụng cá nhân hoặc làm quà",
    ],
    category: "Combo",
    stock: 25,
    hot: true,
    newProduct: false,
    sale: true,
  },

  {
    id: 46,
    name: "Combo trải nghiệm Arabica",
    price: 399000,
    oldPrice: 450000,
    image: "./images/combo-arabica.jpg",
    shortDescription:
      "Combo nhiều dòng Arabica dành cho người muốn khám phá hương vị.",
    longDescription:
      "Combo trải nghiệm Arabica gồm nhiều dòng cà phê với đặc điểm hương vị khác nhau. Người dùng có thể so sánh độ chua, hương thơm và hậu vị để tìm ra phong cách cà phê phù hợp với mình.",
    details: [
      "Loại sản phẩm: Combo cà phê",
      "Dòng cà phê: Arabica",
      "Số loại: 3 loại",
      "Mức rang: Khác nhau",
      "Mục đích: Trải nghiệm hương vị",
      "Phù hợp: Người mới tìm hiểu Arabica",
    ],
    category: "Combo",
    stock: 18,
    hot: true,
    newProduct: true,
    sale: true,
  },

  {
    id: 47,
    name: "Combo Pour Over Starter",
    price: 459000,
    oldPrice: 520000,
    image: "./images/combo-pour-over.jpg",
    shortDescription:
      "Bộ khởi đầu gồm V60, giấy lọc và cà phê Arabica rang vừa.",
    longDescription:
      "Combo Pour Over Starter cung cấp những dụng cụ cơ bản để bắt đầu pha cà phê Pour Over tại nhà. Bộ sản phẩm phù hợp với người mới làm quen với pha thủ công mà không cần mua từng món riêng lẻ.",
    details: [
      "Dụng cụ gồm: V60",
      "Phụ kiện: Giấy lọc",
      "Cà phê: Arabica rang vừa",
      "Phương pháp pha: Pour Over",
      "Đối tượng: Người mới bắt đầu",
      "Sử dụng: Pha cà phê tại nhà",
    ],
    category: "Combo",
    stock: 15,
    hot: true,
    newProduct: true,
    sale: true,
  },

  {
    id: 48,
    name: "Combo Cold Brew tại nhà",
    price: 349000,
    oldPrice: 390000,
    image: "./images/combo-cold-brew.jpg",
    shortDescription:
      "Bộ bình pha và cà phê túi lọc dành cho cold brew tại nhà.",
    longDescription:
      "Combo Cold Brew tại nhà gồm bình pha có lõi lọc và các túi cà phê chuyên dùng cho chiết xuất lạnh. Bộ sản phẩm phù hợp với người mới bắt đầu và muốn pha cà phê lạnh đơn giản.",
    details: [
      "Dụng cụ gồm: Bình Cold Brew",
      "Cà phê: Túi lọc pha lạnh",
      "Phương pháp pha: Ngâm lạnh",
      "Thời gian pha: 8 - 12 giờ",
      "Đối tượng: Người mới bắt đầu",
      "Phù hợp: Sử dụng tại nhà",
    ],
    category: "Combo",
    stock: 17,
    hot: false,
    newProduct: true,
    sale: true,
  },

  {
    id: 49,
    name: "Hộp quà cà phê Premium",
    price: 499000,
    oldPrice: 550000,
    image: "./images/gift-premium.jpg",
    shortDescription: "Hộp quà gồm cà phê tuyển chọn và bộ dụng cụ pha cơ bản.",
    longDescription:
      "Hộp quà cà phê Premium kết hợp các dòng cà phê tuyển chọn cùng một số dụng cụ pha cơ bản. Sản phẩm phù hợp làm quà cho bạn bè, đồng nghiệp hoặc những người yêu thích cà phê.",
    details: [
      "Loại sản phẩm: Hộp quà",
      "Sản phẩm chính: Cà phê tuyển chọn",
      "Dụng cụ đi kèm: Có",
      "Bao bì: Hộp quà",
      "Phù hợp: Sinh nhật, lễ, sự kiện",
      "Đối tượng: Người yêu cà phê",
    ],
    category: "Quà tặng",
    stock: 12,
    hot: true,
    newProduct: true,
    sale: true,
  },

  {
    id: 50,
    name: "Hộp quà cà phê Việt Nam",
    price: 359000,
    oldPrice: 399000,
    image: "./images/gift-vietnam.jpg",
    shortDescription:
      "Hộp quà cà phê rang xay kết hợp phin theo phong cách Việt Nam.",
    longDescription:
      "Hộp quà cà phê Việt Nam mang đến trải nghiệm pha phin truyền thống với cà phê rang xay và dụng cụ pha đi kèm. Bộ sản phẩm có phong cách gần gũi và phù hợp làm quà trong nhiều dịp.",
    details: [
      "Loại sản phẩm: Hộp quà",
      "Cà phê: Cà phê rang xay",
      "Dụng cụ đi kèm: Phin",
      "Phong cách: Cà phê Việt Nam",
      "Bao bì: Hộp quà",
      "Phù hợp: Quà tặng cá nhân và doanh nghiệp",
    ],
    category: "Quà tặng",
    stock: 20,
    hot: false,
    newProduct: true,
    sale: true,
  },
];
